// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using System;
using System.Runtime.InteropServices;

namespace Valve.VR
{
    public abstract class SteamVR_Action_List : ScriptableObject
    {
        public SteamVR_ActionSet actionSet;
        public SteamVR_ActionDirections listDirection;
        public SteamVR_Action[] actions;
    }
}